# Generated by Django 4.1.7 on 2023-03-25 06:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.TextField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('account_balance', models.CharField(max_length=255)),
                ('possition', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paper_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(unique=True)),
                ('variety', models.CharField(max_length=255)),
                ('tradingsymbol', models.CharField(max_length=255)),
                ('symboltoken', models.CharField(max_length=255)),
                ('transactiontype', models.CharField(max_length=255)),
                ('exchange', models.CharField(max_length=255)),
                ('ordertype', models.CharField(max_length=255)),
                ('producttype', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('squareoff', models.CharField(max_length=255)),
                ('stoploss', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategymain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_index', models.CharField(choices=[('BANKNIFTY', 'BANKNIFTY'), ('NIFTY', 'NIFTY'), ('FINNIFTY', 'FINNIFTY')], max_length=100)),
                ('strategy_start_time', models.CharField(max_length=255)),
                ('strategy_end_time', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_index', models.CharField(choices=[('BANKNIFTY', 'BANKNIFTY'), ('NIFTY', 'NIFTY'), ('FINNIFTY', 'FINNIFTY')], max_length=100)),
                ('which_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=8)),
                ('which_time_start', models.CharField(blank=True, max_length=20)),
                ('which_time_end', models.CharField(blank=True, max_length=20)),
                ('sell_ce_price', models.CharField(blank=True, max_length=255)),
                ('sell_pe_price', models.CharField(blank=True, max_length=255)),
                ('ce_sell_profit_type', models.CharField(blank=True, max_length=255)),
                ('ce_sell_profit_value', models.CharField(blank=True, max_length=255)),
                ('pe_sell_profit_type', models.CharField(blank=True, max_length=255)),
                ('pe_sell_profit_value', models.CharField(blank=True, max_length=255)),
                ('ce_sell_sl_type', models.CharField(blank=True, max_length=255)),
                ('ce_sell_sl_value', models.CharField(blank=True, max_length=255)),
                ('pe_sell_sl_type', models.CharField(blank=True, max_length=255)),
                ('pe_sell_sl_value', models.CharField(blank=True, max_length=255)),
                ('ce_buy_price', models.CharField(blank=True, max_length=255)),
                ('pe_buy_price', models.CharField(blank=True, max_length=255)),
                ('nw_ce_buy_price', models.CharField(blank=True, max_length=255)),
                ('nw_pe_buy_price', models.CharField(blank=True, max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lot', models.IntegerField()),
                ('position', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=100)),
                ('option_type', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=100)),
                ('expiry', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('NEXT WEEKLY', 'NEXT WEEKLY'), ('MONTHLY', 'MONTHLY')], max_length=100)),
                ('strike_criteria_type', models.CharField(choices=[('STRIKE TYPE', 'STRIKE TYPE'), ('PREMIUM RANGE', 'PREMIUM RANGE'), ('CLOSEST PREMIUM', 'CLOSEST PREMIUM')], max_length=100)),
                ('strike_criteria_lower_range', models.IntegerField(null=True)),
                ('strike_criteria_upper_range', models.IntegerField(null=True)),
                ('strike_criteria_strike_type', models.CharField(max_length=100, null=True)),
                ('strike_criteria_premium', models.IntegerField(null=True)),
                ('take_profit_type', models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=100)),
                ('take_profit_value', models.IntegerField()),
                ('stop_loss_type', models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=100)),
                ('stop_loss_value', models.IntegerField()),
                ('trail_stop_loss_type', models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=100)),
                ('trail_stop_loss_value_one', models.IntegerField()),
                ('trail_stop_loss_value_two', models.IntegerField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('strategy_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_data_id', to='core.strategymain')),
            ],
        ),
    ]
