# Generated by Django 4.1.7 on 2023-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyone',
            name='ce_buy_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='current_expiry_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='nw_ce_buy_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='nw_pe_buy_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='pe_buy_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='repeat_order_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='sell_ce_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategyone',
            name='sell_pe_lot',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
