# Generated by Django 4.1.7 on 2023-06-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_strategyone_repeat_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_orders',
            name='match_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper_orders',
            name='name_of_index',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper_orders',
            name='position_close',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='FALSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategyone',
            name='ce_sell_profit_type',
            field=models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='strategyone',
            name='ce_sell_sl_type',
            field=models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='strategyone',
            name='pe_sell_profit_type',
            field=models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='strategyone',
            name='pe_sell_sl_type',
            field=models.CharField(choices=[('POINTS', 'POINTS'), ('PERCENTAGE', 'PERCENTAGE')], max_length=255),
        ),
    ]
